// {
//   name: "Rodrigo Caio",
//   short_name: "R. Caio",
//   num: 3,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823395/flamengo_new/caio_m8akvq.png",
//   pos: "D",
// },
// {
//   name: "David Luiz",
//   short_name: "D. Luiz",
//   num: 23,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823393/flamengo_new/davidluiz_tlgtmt.png",
//   pos: "D",
// },
// {
//   name: "Santos",
//   num: 1,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823395/flamengo_new/santos_bkb964.png",
//   pos: "G",
// },
// {
//   name: "Matheuzinho",
//   short_name: "Matheuzinho",
//   apelido: "Matheus França Silva",
//   num: 34,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823393/flamengo_new/matheuzinho_ghhn3k.png",
//   pos: "LD",
// },  // {
//   name: "Filipe Luis",
//   short_name: "F. Luis",
//   num: 16,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/filipeluis_sho8i7.png",
//   pos: "LE",
// },
// {
//   name: "Thiago Maia",
//   short_name: "T. Maia",
//   num: 8,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/tmaia_kvduft.png",
//   pos: "MD",
// },
// {
//   name: "A. Vidal",
//   short_name: "Vidal",
//   apelido: "Arturo Vidal",
//   num: 32,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/vidal_luvygz.png",
//   pos: "MD",
// },
// {
//   name: "Éverton Ribeiro",
//   short_name: "É. Ribeiro",
//   apelido: "miteiro",
//   num: 7,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/evertonribeiro_nt9dab.png",
//   pos: "MA",
// },
// {
//   name: "Gabriel",
//   short_name: "Gabigol",
//   apelido: "Gabriel Gabigol Barbosa",
//   num: 10,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/gabigol_kn7fm0.png",
//   pos: "A",
// },
// {
//   name: "Fabricio Bruno",
//   short_name: "F. Bruno",
//   num: 15,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823393/flamengo_new/fabriciobruno_k0gzkk.png",
//   pos: "D",
// },
// {
//   name: "Pablo",
//   apelido: "Pablo do Nascimento Castro",
//   num: 30,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823393/flamengo_new/pablo_qcwtdw.png",
//   pos: "D",
// },
// {
//   name: "Matheus França",
//   short_name: "M. França",
//   apelido: "Matheus França de Oliveira",
//   num: 42,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823395/flamengo_new/mfranca_yby8sm.png",
//   pos: "MA",
// },
// {
//   name: "Vitor Hugo",
//   short_name: "V. Hugo",
//   num: 29,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680823394/flamengo_new/vitorhugo_m7ye2x.png",
//   pos: "MA",
// },
// {
//   name: "Mateus Lima",
//   short_name: "Mateusão",
//   num: 46,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1680741412/flamengo_new/mateusao_r0o6gz.png",
//   pos: "A",
// },
// {
//   name: "Igor Jesus",
//   short_name: "Igor",
//   num: 48,
//   img: "https://res.cloudinary.com/raphaelmmachado/image/upload/v1683062182/flamengo/igor-jesus-1_xgkzri.png",
//   pos: "MD",
// },
